version: '3.8'  # 添加 version 字段

services:
  derper:
    image: thinker007/tailscale_ip_derper
    container_name: tailscale_ip_derper
    environment:
      - TZ=Asia/Shanghai
      - DERP_CERT_MODE=manual
      - DERP_ADDR=:443
      - DERP_STUN=true
      - DERP_HTTP_PORT=-1
      - DERP_STUN_PORT=3478
      - DERP_DOMAIN=114.114.114.114 #改为ip
      - DERP_CERT_DIR=/app/certs
      - DERP_VERIFY_CLIENTS=true
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - ./certs:/app/certs
    ports:
      - 443:443
      - 3478:3478/udp
    restart: always
